# Generated by Django 6.0.1 on 2026-02-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Marca')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='shop_brand_name_c466ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.category', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('base_specs', models.JSONField(blank=True, default=dict, null=True, verbose_name='Especificaciones Base')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Variante')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU (Código único de inventario)')),
                ('attributes', models.JSONField(blank=True, default=dict, null=True, verbose_name='Atributos Específicos (ej: color, talla)')),
                ('images', models.JSONField(blank=True, default=list, null=True, verbose_name='URLs de Imágenes')),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso en gramos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('is_master', models.BooleanField(default=False, verbose_name='¿Es la Variante del producto Principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='Marca')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='shop_catego_name_289c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='shop_produc_name_a2070e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='shop_produc_categor_d249e3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='shop_produc_created_ed077b_idx'),
        ),
        migrations.AddIndex(
            model_name='product_variant',
            index=models.Index(fields=['name'], name='shop_produc_name_6eca20_idx'),
        ),
        migrations.AddIndex(
            model_name='product_variant',
            index=models.Index(fields=['sku'], name='shop_produc_sku_428109_idx'),
        ),
        migrations.AddIndex(
            model_name='product_variant',
            index=models.Index(fields=['product'], name='shop_produc_product_c6141d_idx'),
        ),
        migrations.AddIndex(
            model_name='product_variant',
            index=models.Index(fields=['brand'], name='shop_produc_brand_i_28b034_idx'),
        ),
    ]
