# Generated by Django 6.0.1 on 2026-02-17 20:54

import django.db.models.deletion
import shop.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.get_upload_path, verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto Alternativo (SEO)')),
                ('is_main', models.BooleanField(default=False, verbose_name='¿Es la principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Variante')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.UUIDField(default=uuid.uuid7, editable=False, unique=True, verbose_name='SKU (Código único de inventario)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción de la Variante')),
                ('attributes', models.JSONField(blank=True, default=dict, null=True, verbose_name='Atributos Específicos (ej: color, talla)')),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso en gramos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Base')),
                ('is_master', models.BooleanField(default=False, verbose_name='¿Es la Variante del producto Principal?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name_plural': 'Variantes de Producto',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='product_variant',
            name='shop_produc_name_6eca20_idx',
        ),
        migrations.RemoveIndex(
            model_name='product_variant',
            name='shop_produc_sku_428109_idx',
        ),
        migrations.RemoveIndex(
            model_name='product_variant',
            name='shop_produc_product_c6141d_idx',
        ),
        migrations.RemoveIndex(
            model_name='product_variant',
            name='shop_produc_brand_i_28b034_idx',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.productvariant', verbose_name='Variante'),
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product_variant',
            name='product',
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['name'], name='shop_produc_name_035698_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='shop_produc_sku_e6b8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='shop_produc_product_220f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['brand'], name='shop_produc_brand_i_1885b3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['created_at'], name='shop_produc_created_cfab73_idx'),
        ),
        migrations.DeleteModel(
            name='Product_Variant',
        ),
    ]
